<?php
require_once("header.php");
?>
<?php
require_once("./Templates/banner_area.php");
require_once("./Templates/_product_detail.php");
require_once("./Templates/banner_ads.php");
require_once("./Templates/blog.php");
?>
<?php
require_once("footer.php");
?>